jtype: Flow
version: '1'
with:
  port: 8081
  protocol: http
  cors: true
executors:
  - name: clip_t
    uses:
      jtype: CLIPEncoder
      with:
        name: ViT-B/32
      metas:
        py_modules:
          - clip_server.executors.clip_torch
